components/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView 

from .views import SignUpView, UsersListView, UsersUpdateView, logout_view, ProfileUpdateUserView, UserDeleteView

app_name = "accounts"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup', ),
    path('login/', LoginView.as_view(redirect_authenticated_user=True),name='login', ),
    path('profile/', ProfileUpdateUserView.as_view(), name='profile'),
    path('users/', UsersListView.as_view(), name='users'),
    path('edit_user/<int:pk>', UsersUpdateView.as_view(), name='updateUser'),
    path('delete_user/<int:pk>', UserDeleteView.as_view(), name='deleteUser'),
    path('logout/', logout_view, name='logout'),
    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='password_reset_form.html',
         email_template_name="password_reset_email.html",
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),

    path('password_reset_<uidb64>_<token>/', PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ), name='password_reset_complete'),
]

gmayo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('components.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("crud/", include("components.crud.urls")),
    path("dashboard/", include("components.dashboard.urls")),
    path("report/", include("components.reportes.urls")),
    path('', RedirectView.as_view(url='/dashboard')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{title}}</title>
<link rel="icon" type="image/x-icon" href="/static/images/icons/favicon.ico">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="/static/fonts/sourceSansFamily.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/adminlte.min.css">
  <!-- Datatable -->

  <link rel="stylesheet" type="text/css" href="/static/plugins/datatables/datatables.min.css"/>

</head>
{% block body %}

{% endblock %}
</html>

templates/body.html
{%include "base.html"%}
{%include "sidebar.html"%}
{%block body%}
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">

      </li>

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">




      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {%block sidebar%} 
  
  {%endblock%} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{title2}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/dashboard/home">Inicio</a></li>
              <li class="breadcrumb-item active">{{title2}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      {%block content%}

      {%endblock%}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Versión</b> 1.0
    </div>
    <strong>Gmayo 2022 .</strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="/static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/dist/js/demo.js"></script>
<script src="/static/scripts/replace.js"></script>


      {%block scripts%}

      {%endblock%}


</body>
{%endblock%}

templates/password_reset_complete.html
{% load widget_tweaks %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Gmayo: Gestor de Proyectos</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/ico" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title">
					<img id="loginLogo" src="/static/images/logo_2.png" alt="Bienvenido a Gmayo">
				</div>

				<p style="text-align:center;">{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

				<a class="login100-form-btn" href="{%url  'login' %}">{% translate 'Log in' %}</a>
			
			
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

templates/password_reset_confirm.html
{% load widget_tweaks %}
{% load i18n static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Gmayo: Gestor de Proyectos</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/ico" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title">
					<img id="loginLogo" src="/static/images/logo_2.png" alt="Bienvenido a Gmayo">
				</div>

				{% if validlink %}

				<p style="text-align:center;">{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
				
				<form class="login100-form validate-form" method="POST">
					<fieldset class="module aligned">

					{% csrf_token %}
				

					<div class="form-row field-password1 wrap-input100 validate-input m-b-18">
						
						{{ form.new_password1.errors }}
						<label class="label-input100" for="id_new_password1">{% translate 'New password:' %}</label>
						{{ form.new_password1|add_class:'input100' }}
						<span class="focus-input100"></span>
					</div>
		
					<div class="form-row field-password2 wrap-input100 validate-input m-b-18">
						{{ form.new_password2.errors }}
						<label class="label-input100" for="id_new_password2">{% translate 'Confirm password:' %}</label>
						{{ form.new_password2|add_class:'input100' }}
						<span class="focus-input100"></span>

					</div>
					<br>
					
					<input type="submit" class="login100-form-btn" value="{% translate 'Change my password' %}">
				</fieldset>
				</form>
				
				{% else %}
				
				<p style="text-align:justify; padding:20px">{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
				
				{% endif %}
					
					</div>

					
					</div>

					

					
				
				
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

templates/password_reset_done.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Gmayo: Gestor de Proyectos</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/ico" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title">
					<img id="loginLogo" src="/static/images/logo_2.png" alt="Bienvenido a Gmayo">
				</div>
			
				<div style="text-align:justify; padding:40px;">
					
					{% load i18n %}
					<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
				
				<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
				
	
				</div>
			
				
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/password_reset_form.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Gmayo: Gestor de Proyectos</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/ico" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title">
					<img id="loginLogo" src="/static/images/logo_2.png" alt="Bienvenido a Gmayo">
				</div>

				<form class="login100-form validate-form" method="POST">

					<p style="text-align:justify;">Si olvidó su contraseña, ingrese su correo registrado en el perfil y le enviaremos instrucciones para restablecerla </p>
					{% csrf_token %}
					<div class="wrap-input100 validate-input m-b-26" data-validate="Usuario es requerido">
						<label class="label-input100" for="username">Email:</label>
						
						{{ form.email|add_class:'input100' }}

						<span class="focus-input100"></span>
					</div>

					

					<div class="flex-sb-m w-full p-b-30">


						<div >
							

						</div>
					</div>

					<div class="container-login100-form-btn">
							<input type="submit" value="Enviame las instrucciones" class="login100-form-btn" />
						
			
					
					</div>
					<input type="hidden" name="next" value="{{ next }}" />
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

templates/sidebar.html
{%block sidebar%}
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/dashboard/home" class="brand-link">
      <img src="/static/images/logo_2.png" alt="gmayo Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light"> GMAYO</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/images/avatar/avatar1.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="/accounts/profile" class="d-block">{{request.user}} <br> <p style="font-size: 80%;">({{request.user.rol}})</p> </a>
        </div>
      </div>



      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          
          {% if request.user.rol != "Coord. Proyectos"%}
               <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="far fa-plus-square"></i>
              <p>
                Añadir
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                  {%if request.user.rol == "ADMINISTRADOR"%}
                <a href="/crud/agregar/" class="nav-link">
                    {%endif%}
                  {%if request.user.rol != "ADMINISTRADOR"%}
                <a href="/crud/agregarProyecto/" class="nav-link">
                    {%endif%}
                    <i class="far fa-newspaper"></i>
                  <p>Proyecto</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/crud/agregarCaso" class="nav-link">
                  <i class="fas fa-search-location"></i>
                  <p>Caso</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/crud/agregarResponsable" class="nav-link">
                  <i class="fas fa-chalkboard-teacher"></i>                  <p>Docentes</p>
                </a>
              </li>
            </ul>
          </li>
          {%endif%}
          <li class="nav-header">Ver</li>
          <li class="nav-item">
                <a href="/report/proyectos" class="nav-link">
                    <i class="far fa-newspaper"></i>
                  <p>Proyectos</p>
                </a>
              </li>
          <li class="nav-item">
                <a href="/crud/casos" class="nav-link">
                  <i class="fas fa-search-location"></i>
                  <p>Casos</p>
                </a>
              </li>
          <li class="nav-item">
                <a href="/crud/responsables" class="nav-link">
                  <i class="fas fa-chalkboard-teacher"></i>                  <p>Docentes</p>
                </a>
              </li>
          <li class="nav-header">GMAYO</li>
          {%if request.user.rol == "ADMINISTRADOR"%}
          <li class="nav-item">
         
          <a href="/accounts/users/" class="nav-link">
            <i class="fas fa-user-friends"></i>
            <p>  Usuarios</p>

          </a>
              </li>
              {%endif%}
           
          <li class="nav-item">
                <a href="/dashboard/" class="nav-link">
                  <i class="fas fa-info-circle"></i>
                  <p>Información del sistema</p>
                </a>
              </li>
          <li class="nav-item">
            <a href="/accounts/logout" class="nav-link">
                <i class="fas fa-door-open text-danger"></i>
              <p class="text">Cerrar Sesión</p>
            </a>
          </li>



        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

{%endblock%}